### ISSUE TITLE
It is still working?

### ISSUE THREAD

**Issue by diepnt90** [Destroyer616/Lenovo-Thinkstation-P330-Tiny-Hackintosh#2]
Hi,

I have the same PC P330 tiny and copied your EFI for the Ventura setup but failed to install it.
Right after choosing install Ventura i got this
![image](https://github.com/Destroyer616/Lenovo-Thinkstation-P330-Tiny-Hackintosh/assets/18731180/983f3077-40fc-422d-ad2e-38b4deaa7dcd)

**Comment by saikiran6-1-6** [comment]
Yes, it is still working for me.
![SCR-20240227-oflc](https://github.com/Destroyer616/Lenovo-Thinkstation-P330-Tiny-Hackintosh/assets/46772654/2bd38f02-0a80-4976-9558-d9c418dd82a5)

![SCR-20240227-offt](https://github.com/Destroyer616/Lenovo-Thinkstation-P330-Tiny-Hackintosh/assets/46772654/a3dab731-78d1-41e1-b064-f234b920cd3b)

Check if those options are set in BIOS.

**Comment by diepnt90** [comment]
Thank you. it works. it is due to my Hynix ssd name. replaced with WD solved the issue
